#!/usr/bin/env python3

from math import inf
import re
import requests

url = "https://api.warframe.market/v1/auctions"
response = requests.get(url)

def get_weapon():
    weapon = input("weapon: ")
    if any(char.isdigit() for char in weapon) or len(weapon) == 0:
        print("invalid name")
        exit(84)
    return re.sub(r'[^a-zA-Z]', '_', weapon.lower())

def get_attributes(item):
    for stat in item['item']['attributes']:
        print(f"{stat['url_name']}: {stat['value']}")
    print()

def get_price(item):
    if item['buyout_price'] != item['starting_price']:
        if item['buyout_price'] == None:
            print(f"starting price : {item['starting_price']} -> auction, buyout price : ∞")
        else:
            print(f"starting price : {item['starting_price']} -> auction, buyout price : {item['buyout_price']}")
    else:
        print(f"statrting price : {item['starting_price']}")

if response.status_code == 200:
    min = inf;
    id = "";
    weapon = get_weapon()
    items = response.json()
    for item in items['payload']['auctions']:
        if item['item']['weapon_url_name'] == weapon:
            get_price(item)
            print("https://warframe.market/auction/", item['id'], sep="")
            get_attributes(item)
else:
    print(f"Error: {response.status_code}")

