#!/usr/bin/env python3

from dotenv import load_dotenv
import os
import asyncio
from func.auctions import check_auctions
from bot.commands import bot

load_dotenv()

TOKEN = os.getenv("DISCORD_BOT_TOKEN")
CHANNEL_ID = int(os.getenv("CHANNEL_ID"))

async def auction_loop(channel):
    while True:
        await check_auctions(channel)
        await asyncio.sleep(120)

@bot.event
async def on_ready():
    await bot.tree.sync(guild=None)
    print(f"Logged in as {bot.user}")
    channel = bot.get_channel(CHANNEL_ID)
    if channel is not None:
        bot.loop.create_task(auction_loop(channel))
    else:
        print("Channel not found.")

if __name__ == "__main__":
    bot.run(TOKEN)
