#!/usr/bin/env python3

import os
import asyncio
from func.auctions import check_auctions
from bot.commands import bot

TOKEN = os.getenv("DISCORD_BOT_TOKEN")
CHANNEL_ID = 1329891514976829520

async def auction_loop(channel):
    while True:
        await check_auctions(channel)
        await asyncio.sleep(120)

@bot.event
async def on_ready():
    print(f"Logged in as {bot.user}")
    channel = bot.get_channel(CHANNEL_ID)
    if channel is not None:
        bot.loop.create_task(auction_loop(channel))
    else:
        print("Channel not found.")

if __name__ == "__main__":
    bot.run(TOKEN)
