weapon_choices = {
  "Shedu": "shedu",
  "Bubonico": "bubonico",
  "Cernos": "cernos",
  "Cernos Prime": "cernos_prime",
  "Cinta": "cinta",
  "Daikyu": "daikyu",
  "Daikyu Prime": "daikyu_prime",
  "Dread": "dread",
  "Evensong": "evensong",
  "Kuva Bramma": "kuva_bramma",
  "Lenz": "lenz",
  "MK1-Paris": "mk1-paris",
  "Mutalist Cernos": "mutalist_cernos",
  "Nataruk": "nataruk",
  "Paris": "paris",
  "Paris Prime": "paris_prime",
  "Prisma Lenz": "prisma_lenz",
  "Proboscis Cernos": "proboscis_cernos",
  "Rakta Cernos": "rakta_cernos",
  "Attica": "attica",
  "Zhuge": "zhuge",
  "Zhuge Prime": "zhuge_prime",
  "Nagantaka": "nagantaka",
  "Nagantaka Prime": "nagantaka_prime",
  "Artemis Bow": "artemis_bow",
  "Artemis Bow Prime": "artemis_bow_prime",
  "Lizzie": "lizzie",
  "Neutralizer": "neutralizer",
  "Carmine Penta": "carmine_penta",
  "Penta": "penta",
  "Secura Penta": "secura_penta",
  "Tenet Envoy": "tenet_envoy",
  "Ogris": "ogris",
  "Kuva Ogris": "kuva_ogris",
  "Kuva Tonkor": "kuva_tonkor",
  "Kuva Zarr": "kuva_zarr",
  "Tonkor": "tonkor",
  "Torid": "torid",
  "Zarr": "zarr",
  "Simulor": "simulor",
  "Synoid Simulor": "synoid_simulor",
  "AX-52": "ax-52",
  "Acceltra": "acceltra",
  "Acceltra Prime": "acceltra_prime",
  "Baza": "baza",
  "Baza Prime": "baza_prime",
  "Boltor": "boltor",
  "Boltor Prime": "boltor_prime",
  "Braton": "braton",
  "Braton Prime": "braton_prime",
  "Braton Vandal": "braton_vandal",
  "Dera": "dera",
  "Dera Vandal": "dera_vandal",
  "Gotva Prime": "gotva_prime",
  "Grakata": "grakata",
  "Karak": "karak",
  "Karak Wraith": "karak_wraith",
  "Kuva Karak": "kuva_karak",
  "MK1-Braton": "mk1-braton",
  "Prisma Grakata": "prisma_grakata",
  "Prisma Tetra": "prisma_tetra",
  "Reconifex": "reconifex",
  "Telos Boltor": "telos_boltor",
  "Tenet Flux Rifle": "tenet_flux_rifle",
  "Tetra": "tetra",
  "Alternox": "alternox",
  "Kuva Quartakk": "kuva_quartakk",
  "Aeolak": "aeolak",
  "Ambassador": "ambassador",
  "EFV-5 Jupiter": "efv-5_jupiter",
  "Quellor": "quellor",
  "Stahlta": "stahlta",
  "Basmu": "basmu",
  "Panthera": "panthera",
  "Panthera Prime": "panthera_prime",
  "Argonak": "argonak",
  "Buzlok": "buzlok",
  "Fulmin": "fulmin",
  "Fulmin Prime": "fulmin_prime",
  "Mutalist Quanta": "mutalist_quanta",
  "Phenmor": "phenmor",
  "Stradavar": "stradavar",
  "Stradavar Prime": "stradavar_prime",
  "Tenet Tetra": "tenet_tetra",
  "Trumna": "trumna",
  "Trumna Prime": "trumna_prime",
  "Zenith": "zenith",
  "Battacor": "battacor",
  "Gorgon": "gorgon",
  "Gorgon Wraith": "gorgon_wraith",
  "Prisma Gorgon": "prisma_gorgon",
  "Soma": "soma",
  "Soma Prime": "soma_prime",
  "Supra": "supra",
  "Supra Vandal": "supra_vandal",
  "Tenora": "tenora",
  "Tenora Prime": "tenora_prime",
  "Burston": "burston",
  "Burston Prime": "burston_prime",
  "Coda Hema": "coda_hema",
  "Dex Sybaris": "dex_sybaris",
  "Hema": "hema",
  "Paracyst": "paracyst",
  "Quartakk": "quartakk",
  "Sybaris": "sybaris",
  "Sybaris Prime": "sybaris_prime",
  "Tiberon": "tiberon",
  "Higasa": "higasa",
  "Harpak": "harpak",
  "Hind": "hind",
  "Kuva Hind": "kuva_hind",
  "Tiberon Prime": "tiberon_prime",
  "Miter": "miter",
  "Opticor": "opticor",
  "Opticor Vandal": "opticor_vandal",
  "Amprex": "amprex",
  "Coda Synapse": "coda_synapse",
  "Flux Rifle": "flux_rifle",
  "Glaxion": "glaxion",
  "Glaxion Vandal": "glaxion_vandal",
  "Ignis": "ignis",
  "Ignis Wraith": "ignis_wraith",
  "Synapse": "synapse",
  "Tenet Glaxion": "tenet_glaxion",
  "Quanta": "quanta",
  "Quanta Vandal": "quanta_vandal",
  "Grinlok": "grinlok",
  "Kuva Chakkhurr": "kuva_chakkhurr",
  "Latron": "latron",
  "Latron Prime": "latron_prime",
  "Latron Wraith": "latron_wraith",
  "Prisma Grinlok": "prisma_grinlok",
  "Purgator 1": "purgator_1",
  "Veldt": "veldt",
  "Astilla": "astilla",
  "Astilla Prime": "astilla_prime",
  "Boar": "boar",
  "Boar Prime": "boar_prime",
  "Kuva Sobek": "kuva_sobek",
  "Sobek": "sobek",
  "Cedo": "cedo",
  "Cedo Prime": "cedo_prime",
  "Felarx": "felarx",
  "Kohm": "kohm",
  "Kuva Kohm": "kuva_kohm",
  "Drakgoon": "drakgoon",
  "Kuva Drakgoon": "kuva_drakgoon",
  "Sancti Tigris": "sancti_tigris",
  "Tigris": "tigris",
  "Tigris Prime": "tigris_prime",
  "Convectrix": "convectrix",
  "Phage": "phage",
  "Phantasma": "phantasma",
  "Phantasma Prime": "phantasma_prime",
  "Arca Plasmor": "arca_plasmor",
  "Coda Bassocyst": "coda_bassocyst",
  "Corinth": "corinth",
  "Corinth Prime": "corinth_prime",
  "Exergis": "exergis",
  "Hek": "hek",
  "Kuva Hek": "kuva_hek",
  "MK1-Strun": "mk1-strun",
  "Rauta": "rauta",
  "Steflos": "steflos",
  "Strun": "strun",
  "Strun Prime": "strun_prime",
  "Strun Wraith": "strun_wraith",
  "Tenet Arca Plasmor": "tenet_arca_plasmor",
  "Vaykor Hek": "vaykor_hek",
  "Perigale": "perigale",
  "Lanka": "lanka",
  "Coda Sporothrix": "coda_sporothrix",
  "Komorex": "komorex",
  "Rubico": "rubico",
  "Rubico Prime": "rubico_prime",
  "Snipetron": "snipetron",
  "Snipetron Vandal": "snipetron_vandal",
  "Sporothrix": "sporothrix",
  "Vectis": "vectis",
  "Vectis Prime": "vectis_prime",
  "Vulkar": "vulkar",
  "Vulkar Wraith": "vulkar_wraith",
  "Scourge": "scourge",
  "Scourge Prime": "scourge_prime",
  "Javlok": "javlok",
  "Ferrox": "ferrox",
  "Tenet Ferrox": "tenet_ferrox",
  "Afentis": "afentis",
  "Ballistica": "ballistica",
  "Rakta Ballistica": "rakta_ballistica",
  "Ballistica Prime": "ballistica_prime",
  "Afuris": "afuris",
  "Afuris Prime": "afuris_prime",
  "Akstiletto": "akstiletto",
  "Akstiletto Prime": "akstiletto_prime",
  "Akzani": "akzani",
  "Dex Furis": "dex_furis",
  "Dual Cestra": "dual_cestra",
  "Dual Coda Torxica": "dual_coda_torxica",
  "Kuva Twin Stubbas": "kuva_twin_stubbas",
  "Prisma Twin Gremlins": "prisma_twin_gremlins",
  "Twin Grakatas": "twin_grakatas",
  "Twin Gremlins": "twin_gremlins",
  "Twin Vipers": "twin_vipers",
  "Twin Vipers Wraith": "twin_vipers_wraith",
  "Tenet Diplos": "tenet_diplos",
  "Aksomati": "aksomati",
  "Aksomati Prime": "aksomati_prime",
  "Secura Dual Cestra": "secura_dual_cestra",
  "Akarius": "akarius",
  "Akarius Prime": "akarius_prime",
  "Akjagara": "akjagara",
  "Akjagara Prime": "akjagara_prime",
  "Akbolto": "akbolto",
  "Akbolto Prime": "akbolto_prime",
  "Aklato": "aklato",
  "Aklex": "aklex",
  "Aklex Prime": "aklex_prime",
  "Akmagnus": "akmagnus",
  "Akmagnus Prime": "akmagnus_prime",
  "Akvasto": "akvasto",
  "Akvasto Prime": "akvasto_prime",
  "Dual Toxocyst": "dual_toxocyst",
  "Telos Akbolto": "telos_akbolto",
  "Twin Kohmak": "twin_kohmak",
  "Akbronco": "akbronco",
  "Akbronco Prime": "akbronco_prime",
  "Twin Rogga": "twin_rogga",
  "Dex Pixia": "dex_pixia",
  "Dex Pixia Prime": "dex_pixia_prime",
  "Glory": "glory",
  "Noctua": "noctua",
  "Regulators": "regulators",
  "Regulators Prime": "regulators_prime",
  "Balefire Charger": "balefire_charger",
  "Balefire Charger Prime": "balefire_charger_prime",
  "Azima": "azima",
  "Cestra": "cestra",
  "Furis": "furis",
  "Hystrix": "hystrix",
  "Hystrix Prime": "hystrix_prime",
  "Knell": "knell",
  "Knell Prime": "knell_prime",
  "Kompressa": "kompressa",
  "Kompressa Prime": "kompressa_prime",
  "MK1-Furis": "mk1-furis",
  "Onos": "onos",
  "Riot-848": "riot-848",
  "Stubba": "stubba",
  "Velox": "velox",
  "Velox Prime": "velox_prime",
  "Viper": "viper",
  "Viper Wraith": "viper_wraith",
  "Quatz": "quatz",
  "Stug": "stug",
  "Athodai": "athodai",
  "Cyanex": "cyanex",
  "Kraken": "kraken",
  "Sepulcrum": "sepulcrum",
  "Sicarus": "sicarus",
  "Sicarus Prime": "sicarus_prime",
  "Kuva Kraken": "kuva_kraken",
  "Angstrum": "angstrum",
  "Prisma Angstrum": "prisma_angstrum",
  "Zylok": "zylok",
  "Zylok Prime": "zylok_prime",
  "Atomos": "atomos",
  "Catabolyst": "catabolyst",
  "Coda Catabolyst": "coda_catabolyst",
  "Cycron": "cycron",
  "Embolist": "embolist",
  "Gammacor": "gammacor",
  "Kuva Nukor": "kuva_nukor",
  "Nukor": "nukor",
  "Ocucor": "ocucor",
  "Spectra": "spectra",
  "Spectra Vandal": "spectra_vandal",
  "Synoid Gammacor": "synoid_gammacor",
  "Tenet Cycron": "tenet_cycron",
  "Laetum": "laetum",
  "Epitaph": "epitaph",
  "Epitaph Prime": "epitaph_prime",
  "Tenet Plinx": "tenet_plinx",
  "Acrid": "acrid",
  "Arca Scisco": "arca_scisco",
  "Bolto": "bolto",
  "Coda Tysis": "coda_tysis",
  "EFV-8 Mars": "efv-8_mars",
  "Kulstar": "kulstar",
  "Kuva Seer": "kuva_seer",
  "Lato": "lato",
  "Lato Prime": "lato_prime",
  "Lato Vandal": "lato_vandal",
  "Lex": "lex",
  "Lex Prime": "lex_prime",
  "Magnus": "magnus",
  "Magnus Prime": "magnus_prime",
  "Marelok": "marelok",
  "Plinx": "plinx",
  "Seer": "seer",
  "Sonicor": "sonicor",
  "Tenet Spirex": "tenet_spirex",
  "Tysis": "tysis",
  "Vasto": "vasto",
  "Vasto Prime": "vasto_prime",
  "Vaykor Marelok": "vaykor_marelok",
  "Vesper 77": "vesper_77",
  "Zakti": "zakti",
  "Zakti Prime": "zakti_prime",
  "Zymos": "zymos",
  "Pandero": "pandero",
  "Pandero Prime": "pandero_prime",
  "Pyrana": "pyrana",
  "Pyrana Prime": "pyrana_prime",
  "Kohmak": "kohmak",
  "Brakk": "brakk",
  "Bronco": "bronco",
  "Bronco Prime": "bronco_prime",
  "Detron": "detron",
  "Euphona Prime": "euphona_prime",
  "Kuva Brakk": "kuva_brakk",
  "Mara Detron": "mara_detron",
  "Tenet Detron": "tenet_detron",
  "Aegrit": "aegrit",
  "Castanas": "castanas",
  "Sancti Castanas": "sancti_castanas",
  "Talons": "talons",
  "Cantare": "cantare",
  "Coda Pox": "coda_pox",
  "Despair": "despair",
  "Hikou": "hikou",
  "Hikou Prime": "hikou_prime",
  "Kunai": "kunai",
  "MK1-Kunai": "mk1-kunai",
  "Pox": "pox",
  "Spira": "spira",
  "Spira Prime": "spira_prime",
  "Fusilai": "fusilai",
  "Scyotid": "scyotid",
  "Staticor": "staticor",
  "Grimoire": "grimoire",
  "Ghoulsaw": "ghoulsaw",
  "Ceti Lacera": "ceti_lacera",
  "Dorrclave": "dorrclave",
  "Jat Kusar": "jat_kusar",
  "Lacera": "lacera",
  "Mios": "mios",
  "Garuda Prime Talons": "garuda_prime_talons",
  "Garuda Talons": "garuda_talons",
  "Keratinos": "keratinos",
  "Ripkas": "ripkas",
  "Venka": "venka",
  "Venka Prime": "venka_prime",
  "Ceramic Dagger": "ceramic_dagger",
  "Dark Dagger": "dark_dagger",
  "Heat Dagger": "heat_dagger",
  "Innodem": "innodem",
  "Karyst": "karyst",
  "Karyst Prime": "karyst_prime",
  "Rakta Dark Dagger": "rakta_dark_dagger",
  "Rumblejack": "rumblejack",
  "Sheev": "sheev",
  "Ether Daggers": "ether_daggers",
  "Fang": "fang",
  "Fang Prime": "fang_prime",
  "Nepheri": "nepheri",
  "Okina": "okina",
  "Okina Prime": "okina_prime",
  "Sun & Moon": "sun_&_moon",
  "Dark Split-Sword Dual Swords": "dark_split-sword_dual_swords",
  "Dex Dakra": "dex_dakra",
  "Dual Cleavers": "dual_cleavers",
  "Dual Ether": "dual_ether",
  "Dual Heat Swords": "dual_heat_swords",
  "Dual Ichor": "dual_ichor",
  "Dual Kamas": "dual_kamas",
  "Dual Kamas Prime": "dual_kamas_prime",
  "Dual Keres": "dual_keres",
  "Dual Keres Prime": "dual_keres_prime",
  "Dual Raza": "dual_raza",
  "Dual Skana": "dual_skana",
  "Dual Viciss": "dual_viciss",
  "Dual Zoren": "dual_zoren",
  "Dual Zoren Prime": "dual_zoren_prime",
  "Nami Skyla": "nami_skyla",
  "Nami Skyla Prime": "nami_skyla_prime",
  "Prisma Dual Cleavers": "prisma_dual_cleavers",
  "Twin Basolk": "twin_basolk",
  "Twin Krohkur": "twin_krohkur",
  "Desert Wind": "desert_wind",
  "Desert Wind Prime": "desert_wind_prime",
  "Diwata": "diwata",
  "Diwata Prime": "diwata_prime",
  "Exalted Blade": "exalted_blade",
  "Exalted Prime Blade": "exalted_prime_blade",
  "Exalted Umbra Blade": "exalted_umbra_blade",
  "Iron Staff": "iron_staff",
  "Iron Staff Prime": "iron_staff_prime",
  "Landslide Fists": "landslide_fists",
  "Landslide Fists Prime": "landslide_fists_prime",
  "Shadow Claws": "shadow_claws",
  "Shadow Claws Prime": "shadow_claws_prime",
  "Shadow Clones": "shadow_clones",
  "Shadow Clones Prime": "shadow_clones_prime",
  "Shattered Lash": "shattered_lash",
  "Shattered Lash Prime": "shattered_lash_prime",
  "Valkyr Prime Talons": "valkyr_prime_talons",
  "Valkyr Talons": "valkyr_talons",
  "Whipclaw": "whipclaw",
  "Whipclaw Prime": "whipclaw_prime",
  "Ankyros": "ankyros",
  "Ankyros Prime": "ankyros_prime",
  "Furax": "furax",
  "Furax Wraith": "furax_wraith",
  "MK1-Furax": "mk1-furax",
  "Ruvox": "ruvox",
  "Tekko": "tekko",
  "Tekko Prime": "tekko_prime",
  "Cerata": "cerata",
  "Coda Pathocyst": "coda_pathocyst",
  "Falcor": "falcor",
  "Glaive": "glaive",
  "Glaive Prime": "glaive_prime",
  "Halikar": "halikar",
  "Halikar Wraith": "halikar_wraith",
  "Kestrel": "kestrel",
  "Orvius": "orvius",
  "Pathocyst": "pathocyst",
  "Xoris": "xoris",
  "Redeemer": "redeemer",
  "Redeemer Prime": "redeemer_prime",
  "Sarpa": "sarpa",
  "Stropha": "stropha",
  "Vastilok": "vastilok",
  "Arca Titron": "arca_titron",
  "Coda Motovore": "coda_motovore",
  "Ekhein": "ekhein",
  "Fragor": "fragor",
  "Fragor Prime": "fragor_prime",
  "Heliocor": "heliocor",
  "Jat Kittag": "jat_kittag",
  "Kuva Shildeg": "kuva_shildeg",
  "Magistar": "magistar",
  "Sampotes": "sampotes",
  "Sancti Magistar": "sancti_magistar",
  "Sibear": "sibear",
  "Synoid Heliocor": "synoid_heliocor",
  "Volnus": "volnus",
  "Volnus Prime": "volnus_prime",
  "Wolf Sledge": "wolf_sledge",
  "Dark Split-Sword Heavy Blade": "dark_split-sword_heavy_blade",
  "Galatine": "galatine",
  "Galatine Prime": "galatine_prime",
  "Gram": "gram",
  "Gram Prime": "gram_prime",
  "Masseter": "masseter",
  "Masseter Prime": "masseter_prime",
  "Paracesis": "paracesis",
  "Sarofang": "sarofang",
  "Scindo": "scindo",
  "Scindo Prime": "scindo_prime",
  "Tenet Exec": "tenet_exec",
  "Vitrica": "vitrica",
  "War": "war",
  "Zenistar": "zenistar",
  "Corufell": "corufell",
  "Hespar": "hespar",
  "Thalys": "thalys",
  "Gazal Machete": "gazal_machete",
  "Kama": "kama",
  "Kreska": "kreska",
  "Machete": "machete",
  "Machete Wraith": "machete_wraith",
  "Nami Solo": "nami_solo",
  "Prisma Machete": "prisma_machete",
  "Prova": "prova",
  "Prova Vandal": "prova_vandal",
  "Slaytra": "slaytra",
  "Dex Nikana": "dex_nikana",
  "Dragon Nikana": "dragon_nikana",
  "Nikana": "nikana",
  "Nikana Prime": "nikana_prime",
  "Skiajati": "skiajati",
  "Syam": "syam",
  "Ninkondi": "ninkondi",
  "Ninkondi Prime": "ninkondi_prime",
  "Pulmonars": "pulmonars",
  "Shaku": "shaku",
  "Amanata": "amanata",
  "Cassowar": "cassowar",
  "Edun": "edun",
  "Guandao": "guandao",
  "Guandao Prime": "guandao_prime",
  "Kesheg": "kesheg",
  "Korumm": "korumm",
  "Lesion": "lesion",
  "Orthos": "orthos",
  "Orthos Prime": "orthos_prime",
  "Pupacyst": "pupacyst",
  "Serro": "serro",
  "Sydon": "sydon",
  "Tonbo": "tonbo",
  "Vaykor Sydon": "vaykor_sydon",
  "Destreza": "destreza",
  "Destreza Prime": "destreza_prime",
  "Endura": "endura",
  "Anku": "anku",
  "Caustacyst": "caustacyst",
  "Coda Caustacyst": "coda_caustacyst",
  "Ether Reaper": "ether_reaper",
  "Harmony": "harmony",
  "Hate": "hate",
  "Reaper Prime": "reaper_prime",
  "Tenet Grigori": "tenet_grigori",
  "Venato": "venato",
  "Coda Hirudo": "coda_hirudo",
  "Hirudo": "hirudo",
  "Kogake": "kogake",
  "Kogake Prime": "kogake_prime",
  "Korrudo": "korrudo",
  "Obex": "obex",
  "Prisma Obex": "prisma_obex",
  "Amphis": "amphis",
  "Bo": "bo",
  "Bo Prime": "bo_prime",
  "Broken Scepter": "broken_scepter",
  "Cadus": "cadus",
  "MK1-Bo": "mk1-bo",
  "Tipedo": "tipedo",
  "Tipedo Prime": "tipedo_prime",
  "Ack & Brunt": "ack_&_brunt",
  "Argo & Vel": "argo_&_vel",
  "Cobra & Crane": "cobra_&_crane",
  "Cobra & Crane Prime": "cobra_&_crane_prime",
  "Sigma & Octantis": "sigma_&_octantis",
  "Silva & Aegis": "silva_&_aegis",
  "Silva & Aegis Prime": "silva_&_aegis_prime",
  "Tak & Lug": "tak_&_lug",
  "Tenet Agendus": "tenet_agendus",
  "Broken War": "broken_war",
  "Coda Mire": "coda_mire",
  "Cronus": "cronus",
  "Dakra Prime": "dakra_prime",
  "Dark Sword": "dark_sword",
  "Ether Sword": "ether_sword",
  "Heat Sword": "heat_sword",
  "Jaw Sword": "jaw_sword",
  "Krohkur": "krohkur",
  "Mire": "mire",
  "Pangolin Prime": "pangolin_prime",
  "Pangolin Sword": "pangolin_sword",
  "Plasma Sword": "plasma_sword",
  "Prisma Skana": "prisma_skana",
  "Skana": "skana",
  "Skana Prime": "skana_prime",
  "Boltace": "boltace",
  "Kronen": "kronen",
  "Kronen Prime": "kronen_prime",
  "Ohma": "ohma",
  "Praedos": "praedos",
  "Prisma Ohma": "prisma_ohma",
  "Telos Boltace": "telos_boltace",
  "Tonkkatt": "tonkkatt",
  "Azothane": "azothane",
  "Pennant": "pennant",
  "Tatsu": "tatsu",
  "Tatsu Prime": "tatsu_prime",
  "Tenet Livia": "tenet_livia",
  "Arum Spinosa": "arum_spinosa",
  "Gunsen": "gunsen",
  "Gunsen Prime": "gunsen_prime",
  "Quassus": "quassus",
  "Quassus Prime": "quassus_prime",
  "Vericres": "vericres",
  "Atterax": "atterax",
  "Galvacord": "galvacord",
  "Lecta": "lecta",
  "Scoliac": "scoliac",
  "Secura Lecta": "secura_lecta",
  "Spinnerex": "spinnerex",
  "Verdilac": "verdilac",
  "Tombfinger": "tombfinger",
  "Balla": "balla",
  "Rabvee": "rabvee",
  "Cyath": "cyath",
  "Kronsh": "kronsh",
  "Sepfahn": "sepfahn",
  "Dehtat": "dehtat",
  "Plague Kripath": "plague_kripath",
  "Dokrahm": "dokrahm",
  "Plague Keewar": "plague_keewar",
  "Mewan": "mewan",
  "Ooltha": "ooltha",
  "Rattleguts Secondary": "rattleguts_secondary",
  "Gaze Secondary": "gaze_secondary",
  "Vermisplicer Secondary": "vermisplicer_secondary",
  "Catchmoon Secondary": "catchmoon_secondary",
  "Sporelacer Secondary": "sporelacer_secondary",
  "Tombfinger Secondary": "tombfinger_secondary",
  "Rattleguts Primary": "rattleguts_primary",
  "Gaze Primary": "gaze_primary",
  "Vermisplicer Primary": "vermisplicer_primary",
  "Catchmoon Primary": "catchmoon_primary",
  "Sporelacer Primary": "sporelacer_primary",
  "Dual Decurion": "dual_decurion",
  "Imperator": "imperator",
  "Kuva Ayanga": "kuva_ayanga",
  "Kuva Grattler": "kuva_grattler",
  "Prisma Dual Decurions": "prisma_dual_decurions",
  "Mausolon": "mausolon",
  "Cyngas": "cyngas",
  "Morgha": "morgha",
  "Grattler": "grattler",
  "Imperator Vandal": "imperator_vandal",
  "Phaedra": "phaedra",
  "Corvas": "corvas",
  "Corvas Prime": "corvas_prime",
  "Mandonel": "mandonel",
  "Velocitus": "velocitus",
  "Cortege": "cortege",
  "Larkspur": "larkspur",
  "Larkspur Prime": "larkspur_prime",
  "Fluctus": "fluctus",
  "Dual Decurion Atmosphere": "dual_decurion_atmosphere",
  "Prisma Dual Decurions Atmosphere": "prisma_dual_decurions_atmosphere",
  "Arquebex": "arquebex",
  "Kuva Ayanga Atmosphere": "kuva_ayanga_atmosphere",
  "Kuva Grattler Atmosphere": "kuva_grattler_atmosphere",
  "Morgha Atmosphere": "morgha_atmosphere",
  "Grattler Atmosphere": "grattler_atmosphere",
  "Agkuza": "agkuza",
  "Centaur": "centaur",
  "Kaszas": "kaszas",
  "Knux": "knux",
  "Onorix": "onorix",
  "Prisma Veritux": "prisma_veritux",
  "Rathbone": "rathbone",
  "Veritux": "veritux",
  "Ironbride": "ironbride",
  "Imperator Atmosphere": "imperator_atmosphere",
  "Mausolon Atmosphere": "mausolon_atmosphere",
  "Imperator Vandal Atmosphere": "imperator_vandal_atmosphere",
  "Phaedra Atmosphere": "phaedra_atmosphere",
  "Cyngas Atmosphere": "cyngas_atmosphere",
  "Velocitus Atmosphere": "velocitus_atmosphere",
  "Cortege Atmosphere": "cortege_atmosphere",
  "Larkspur Atmosphere": "larkspur_atmosphere",
  "Larkspur Prime Atmosphere": "larkspur_prime_atmosphere",
  "Fluctus Atmosphere": "fluctus_atmosphere",
  "Corvas Atmosphere": "corvas_atmosphere",
  "Corvas Prime Atmosphere": "corvas_prime_atmosphere",
  "Mandonel Atmosphere": "mandonel_atmosphere",
  "Deconstructor": "deconstructor",
  "Deconstructor Prime": "deconstructor_prime",
  "Akaten": "akaten",
  "Batoten": "batoten",
  "Lacerten": "lacerten",
  "Burst Laser": "burst_laser",
  "Burst Laser Prime": "burst_laser_prime",
  "Prisma Burst Laser": "prisma_burst_laser",
  "Laser Rifle": "laser_rifle",
  "Prime Laser Rifle": "prime_laser_rifle",
  "Deth Machine Rifle": "deth_machine_rifle",
  "Deth Machine Rifle Prime": "deth_machine_rifle_prime",
  "Helstrum": "helstrum",
  "Multron": "multron",
  "Vulcax": "vulcax",
  "Artax": "artax",
  "Tazicor": "tazicor",
  "Verglas": "verglas",
  "Verglas Prime": "verglas_prime",
  "Cryotra": "cryotra",
  "Stinger": "stinger",
  "Sweeper": "sweeper",
  "Sweeper Prime": "sweeper_prime",
  "Vulklok": "vulklok",
}
