weapon_choices = {
    # Primary Weapons (added missing)
    "Boar": "boar",
    "Boar Prime": "boar_prime",
    "Braton Prime": "braton_prime",
    "Braton Vandal": "braton_vandal",
    "Burston Prime": "burston_prime",
    "Cernos Prime": "cernos_prime",
    "Corinth Prime": "corinth_prime",
    "Dera Vandal": "dera_vandal",
    "Dex Sybaris": "dex_sybaris",
    "Glaxion Vandal": "glaxion_vandal",
    "Gorgon": "gorgon",
    "Gorgon Wraith": "gorgon_wraith",
    "Harpak": "harpak",
    "Hind": "hind",
    "Ignis Wraith": "ignis_wraith",
    "Karak Wraith": "karak_wraith",
    "Latron Prime": "latron_prime",
    "Latron Wraith": "latron_wraith",
    "Mutalist Quanta": "mutalist_quanta",
    "Panthera Prime": "panthera_prime",
    "Paris": "paris",
    "Paris Prime": "paris_prime",
    "Prisma Gorgon": "prisma_gorgon",
    "Prisma Grakata": "prisma_grakata",
    "Prisma Grinlok": "prisma_grinlok",
    "Prisma Tetra": "prisma_tetra",
    "Quanta Vandal": "quanta_vandal",
    "Quartakk": "quartakk",
    "Sancti Magistar": "sancti_magistar",
    "Scourge Prime": "scourge_prime",
    "Simulor": "simulor",
    "Snipetron": "snipetron",
    "Snipetron Vandal": "snipetron_vandal",
    "Soma Prime": "soma_prime",
    "Stradavar Prime": "stradavar_prime",
    "Strun Wraith": "strun_wraith",
    "Supra Vandal": "supra_vandal",
    "Sybaris Prime": "sybaris_prime",
    "Synoid Simulor": "synoid_simulor",
    "Talwar": "talwar",
    "Tetra": "tetra",
    "Tiberon Prime": "tiberon_prime",
    "Vandal": "vandal",
    "Vaykor Hek": "vaykor_hek",
    "Veldt": "veldt",
    "Vulkar Wraith": "vulkar_wraith",
    "Zarr": "zarr",

    # Secondary Weapons (added missing)
    "Akbronco Prime": "akbronco_prime",
    "Aksomati Prime": "aksomati_prime",
    "Akstiletto Prime": "akstiletto_prime",
    "Akvasto Prime": "akvasto_prime",
    "Azima": "azima",
    "Ballistica Prime": "ballistica_prime",
    "Bolto": "bolto",
    "Bronco Prime": "bronco_prime",
    "Dex Furis": "dex_furis",
    "Dual Cestra": "dual_cestra",
    "Fusilai": "fusilai",
    "Kohmak": "kohmak",
    "Kraken": "kraken",
    "Kunai": "kunai",
    "Lato Prime": "lato_prime",
    "Lato Vandal": "lato_vandal",
    "Lex Prime": "lex_prime",
    "Marelok": "marelok",
    "Mk1-Furis": "mk1_furis",
    "Mk1-Kunai": "mk1_kunai",
    "Plinx": "plinx",
    "Prisma Angstrum": "prisma_angstrum",
    "Seer": "seer",
    "Spectra": "spectra",
    "Spectra Vandal": "spectra_vandal",
    "Spira Prime": "spira_prime",
    "Stug": "stug",
    "Twin Kohmak": "twin_kohmak",
    "Vasto Prime": "vasto_prime",
    "Vaykor Marelok": "vaykor_marelok",
    "Viper Wraith": "viper_wraith",
    "Zakti Prime": "zakti_prime",

    # Melee Weapons (added missing)
    "Ankyros": "ankyros",
    "Ankyros Prime": "ankyros_prime",
    "Bo": "bo",
    "Bo Prime": "bo_prime",
    "Cadus": "cadus",
    "Ceramic Dagger": "ceramic_dagger",
    "Dakra Prime": "dakra_prime",
    "Dex Dakra": "dex_dakra",
    "Dual Cleavers": "dual_cleavers",
    "Dual Kamas Prime": "dual_kamas_prime",
    "Dual Skana": "dual_skana",
    "Ether Daggers": "ether_daggers",
    "Fang Prime": "fang_prime",
    "Fragor Prime": "fragor_prime",
    "Galatine Prime": "galatine_prime",
    "Glaive": "glaive",
    "Glaive Prime": "glaive_prime",
    "Gram Prime": "gram_prime",
    "Gunsen": "gunsen",
    "Hate": "hate",
    "Jaw Sword": "jaw_sword",
    "Kama": "kama",
    "Kestrel": "kestrel",
    "Kogake Prime": "kogake_prime",
    "Kronen Prime": "kronen_prime",
    "Machete Wraith": "machete_wraith",
    "Mire": "mire",
    "Nami Skyla Prime": "nami_skyla_prime",
    "Nami Solo": "nami_solo",
    "Nikana Prime": "nikana_prime",
    "Obex": "obex",
    "Ohma": "ohma",
    "Orthos Prime": "orthos_prime",
    "Pangolin Sword": "pangolin_sword",
    "Prisma Obex": "prisma_obex",
    "Prisma Skana": "prisma_skana",
    "Redeemer Prime": "redeemer_prime",
    "Reaper Prime": "reaper_prime",
    "Ripkas": "ripkas",
    "Sarpa": "sarpa",
    "Scindo Prime": "scindo_prime",
    "Serro": "serro",
    "Sibear": "sibear",
    "Skiajati": "skiajati",
    "Sydon": "sydon",
    "Tekko Prime": "tekko_prime",
    "Twin Basolk": "twin_basolk",
    "Venka Prime": "venka_prime",
    "Vaykor Sydon": "vaykor_sydon",
    "Volnus": "volnus",
    "Zenistar": "zenistar",

    # Newer Weapons (2022-2023)
    "Felarx": "felarx",
    "Laetum": "laetum",
    "Phenmor": "phenmor",
    "Praedos": "praedos",
    "Innodem": "innodem",
    "Perigale": "perigale",
    "Alternox": "alternox",
    "Corufell": "corufell",
    "Dual Ichor Prime": "dual_ichor_prime",
    "Dual Toxocyst Incarnon": "dual_toxocyst",
    "Latron Incarnon": "latron",
    "Strun Incarnon": "strun",
    "Torid Incarnon": "torid",
    "Burston Incarnon": "burston",
    "Soma Incarnon": "soma",
    "Furis Incarnon": "furis",
    "Lex Incarnon": "lex",
    "Boltor Incarnon": "boltor",
    "Miter Incarnon": "miter",
    "Kunai Incarnon": "kunai",
    "Paris Incarnon": "paris",
    "Braton Incarnon": "braton",
    "Vasto Incarnon": "vasto",
    "Ceramic Dagger Incarnon": "ceramic_dagger",
    "Sibear Incarnon": "sibear",
    "Magistar Incarnon": "magistar",
    "Bo Incarnon": "bo",
    "Furax Incarnon": "furax",
    "Kogake Incarnon": "kogake",
    "Nami Solo Incarnon": "nami_solo",
    "Dual Keres Incarnon": "dual_keres",
    "Anku Incarnon": "anku",
    "Hate Incarnon": "hate",
    "Karak Incarnon": "karak",
    "Kunai Incarnon": "kunai",
    "Lato Incarnon": "lato",
    "Skana Incarnon": "skana",
    "Vasto Incarnon": "vasto",
    "Viper Incarnon": "viper",
    "Zylok Incarnon": "zylok",
    "Gorgon Incarnon": "gorgon",
    "Marelok Incarnon": "marelok",
    "Sobek Incarnon": "sobek",
    "Tigris Incarnon": "tigris",
    "Tonkor Incarnon": "tonkor",
    "Vulkar Incarnon": "vulkar",
    "Zylok Prime": "zylok_prime",
    "Afuris Prime": "afuris_prime",
    "Dual Keres Prime": "dual_keres_prime",
    "Grimoire": "grimoire",
    "Sporothrix": "sporothrix",
    "Tenet Plinx": "tenet_plinx",
    "Tenet Spirex": "tenet_spirex",
    "Tenet Diplos": "tenet_diplos",
    "Tenet Livrea": "tenet_livrea",
    "Tenet Grigori": "tenet_grigori",
    "Tenet Livia": "tenet_livia",
    "Tenet Exec": "tenet_exec",
    "Tenet Agendus": "tenet_agendus",
    "Tenet Ferrox": "tenet_ferrox",
    "Tenet Envoy": "tenet_envoy",
    "Tenet Tetra": "tenet_tetra",
    "Tenet Arca Plasmor": "tenet_arca_plasmor",
    "Tenet Flux Rifle": "tenet_flux_rifle",
    "Tenet Cycron": "tenet_cycron",
    "Tenet Detron": "tenet_detron",
    "Tenet Plinx": "tenet_plinx",
    "Tenet Spirex": "tenet_spirex",
    "Tenet Diplos": "tenet_diplos",
    "Tenet Livrea": "tenet_livrea",
    "Tenet Grigori": "tenet_grigori",
    "Tenet Livia": "tenet_livia",
    "Tenet Exec": "tenet_exec",
    "Tenet Agendus": "tenet_agendus",
    "Tenet Ferrox": "tenet_ferrox",
    "Tenet Envoy": "tenet_envoy",
    "Tenet Tetra": "tenet_tetra",
    "Tenet Arca Plasmor": "tenet_arca_plasmor",
    "Tenet Flux Rifle": "tenet_flux_rifle",
    "Tenet Cycron": "tenet_cycron",
    "Tenet Detron": "tenet_detron",
    "Tenet Plinx": "tenet_plinx",
    "Tenet Spirex": "tenet_spirex",
    "Tenet Diplos": "tenet_diplos",
    "Tenet Livrea": "tenet_livrea",
    "Tenet Grigori": "tenet_grigori",
    "Tenet Livia": "tenet_livia",
    "Tenet Exec": "tenet_exec",
    "Tenet Agendus": "tenet_agendus",
    "Tenet Ferrox": "tenet_ferrox",
    "Tenet Envoy": "tenet_envoy",
    "Tenet Tetra": "tenet_tetra",
    "Tenet Arca Plasmor": "tenet_arca_plasmor",
    "Tenet Flux Rifle": "tenet_flux_rifle",
    "Tenet Cycron": "tenet_cycron",
    "Tenet Detron": "tenet_detron",
}
