weapon_choices = {
    "Acceltra":"acceltra",
    "Amprex":"amprex",
    "Arca Plasmor":"arca_plasmor",
    "Astilla":"astilla",
    "Baza":"baza",
    "Boltor":"boltor",
    "Braton":"braton",
    "Burston":"burston",
    "Cernos":"cernos",
    "Corinth":"corinth",
    "Dera":"dera",
    "Dread":"dread",
    "Fulmin":"fulmin",
    "Glaxion":"glaxion",
    "Grakata":"grakata",
    "Grinlok":"grinlok",
    "Hek":"hek",
    "Ignis":"ignis",
    "Jat Kusar":"jat_kusar",
    "Karak":"karak",
    "Kuva Bramma":"kuva_bramma",
    "Kuva Chakkhurr":"kuva_chakkhurr",
    "Kuva Kohm":"kuva_kohm",
    "Kuva Ogris":"kuva_ogris",
    "Kuva Tonkor":"kuva_tonkor",
    "Lanka":"lanka",
    "Latron":"latron",
    "Lenz":"lenz",
    "Miter":"miter",
    "Mutalist Cernos":"mutalist_cernos",
    "Nagantaka":"nagantaka",
    "Opticor":"opticor",
    "Panthera":"panthera",
    "Paracyst":"paracyst",
    "Phage":"phage",
    "Phantasma":"phantasma",
    "Prisma Grakata":"prisma_grakata",
    "Quanta":"quanta",
    "Rubico":"rubico",
    "Sancti Tigris":"sancti_tigris",
    "Scourge":"scourge",
    "Soma":"soma",
    "Sobek":"sobek",
    "Stradavar":"stradavar",
    "Strun":"strun",
    "Supra":"supra",
    "Sybaris":"sybaris",
    "Synapse":"synapse",
    "Tenora":"tenora",
    "Tigris":"tigris",
    "Tonkor":"tonkor",
    "Torid":"torid",
    "Trumna":"trumna",
    "Vectis":"vectis",
    "Veldt":"veldt",
    "Vulkar":"vulkar",
    "Zenith":"zenith",
    "Zhuge":"zhuge",
    "Acrid":"acrid",
    "Afuris":"afuris",
    "Akarius":"akarius",
    "Akbolto":"akbolto",
    "Akbronco":"akbronco",
    "Akjagara":"akjagara",
    "Aklato":"aklato",
    "Aklex":"aklex",
    "Akmagnus":"akmagnus",
    "Aksomati":"aksomati",
    "Akstiletto":"akstiletto",
    "Akvasto":"akvasto",
    "Angstrum":"angstrum",
    "Arca Scisco":"arca_scisco",
    "Atomos":"atomos",
    "Ballistica":"ballistica",
    "Brakk":"brakk",
    "Bronco":"bronco",
    "Castanas":"castanas",
    "Catabolyst":"catabolyst",
    "Cyanex":"cyanex",
    "Despair":"despair",
    "Detron":"detron",
    "Dual Toxocyst":"dual_toxocyst",
    "Embolist":"embolist",
    "Epitaph":"epitaph",
    "Euphona Prime":"euphona_prime",
    "Furis":"furis",
    "Gammacor":"gammacor",
    "Hikou":"hikou",
    "Hystrix":"hystrix",
    "Knell":"knell",
    "Kompressa":"kompressa",
    "Kraken":"kraken",
    "Kulstar":"kulstar",
    "Kuva Brakk":"kuva_brakk",
    "Kuva Nukor":"kuva_nukor",
    "Kuva Seer":"kuva_seer",
    "Kuva Twin Stubbas":"kuva_twin_stubbas",
    "Lato":"lato",
    "Lex":"lex",
    "Magnus":"magnus",
    "Mara Detron":"mara_detron",
    "Ocucor":"ocucor",
    "Pandero":"pandero",
    "Pox":"pox",
    "Pyrana":"pyrana",
    "Rakta Ballistica":"rakta_ballistica",
    "Sancti Castanas":"sancti_castanas",
    "Secura Dual Cestra":"secura_dual_cestra",
    "Sicarus":"sicarus",
    "Sonicor":"sonicor",
    "Spira":"spira",
    "Staticor":"staticor",
    "Stubba":"stubba",
    "Synoid Gammacor":"synoid_gammacor",
    "Talons":"talons",
    "Tysis":"tysis",
    "Twin Grakatas":"twin_grakatas",
    "Twin Gremlins":"twin_gremlins",
    "Twin Kohmak":"twin_kohmak",
    "Twin Rogga":"twin_rogga",
    "Twin Vipers":"twin_vipers",
    "Vasto":"vasto",
    "Viper":"viper",
    "Xoris":"xoris",
    "Zakti":"zakti",
    "Zylok":"zylok",
    "Anku":"anku",
    "Arca Titron":"arca_titron",
    "Atterax":"atterax",
    "Broken Scepter":"broken_scepter",
    "Broken War":"broken_war",
    "Cerata":"cerata",
    "Ceti Lacera":"ceti_lacera",
    "Cronus":"cronus",
    "Dark Dagger":"dark_dagger",
    "Dark Split-Sword":"dark_split_sword",
    "Dark Sword":"dark_sword",
    "Destreza":"destreza",
    "Dex Dakra":"dex_dakra",
    "Dual Cleavers":"dual_cleavers",
    "Dual Ether":"dual_ether",
    "Dual Heat Swords":"dual_heat_swords",
    "Dual Ichor":"dual_ichor",
    "Dual Kamas":"dual_kamas",
    "Dual Keres":"dual_keres",
    "Dual Raza":"dual_raza",
    "Dual Skana":"dual_skana",
    "Dual Zoren":"dual_zoren",
    "Endura":"endura",
    "Ether Reaper":"ether_reaper",
    "Ether Sword":"ether_sword",
    "Fang":"fang",
    "Fragor":"fragor",
    "Galatine":"galatine",
    "Gazal Machete":"gazal_machete",
    "Gram":"gram",
    "Guandao":"guandao",
    "Halikar":"halikar",
    "Hate":"hate",
    "Heat Dagger":"heat_dagger",
    "Heat Sword":"heat_sword",
    "Hirudo":"hirudo",
    "Jat Kittag":"jat_kittag",
    "Karyst":"karyst",
    "Kesheg":"kesheg",
    "Kogake":"kogake",
    "Korrudo":"korrudo",
    "Krohkur":"krohkur",
    "Kronsh":"kronsh",
    "Lacera":"lacera",
    "Lecta":"lecta",
    "Lesion":"lesion",
    "Machete":"machete",
    "Magistar":"magistar",
    "Mios":"mios",
    "Nami Skyla":"nami_skyla",
    "Nami Solo":"nami_solo",
    "Ninkondi":"ninkondi",
    "Nikana":"nikana",
    "Okina":"okina",
    "Orthos":"orthos",
    "Pangolin Sword":"pangolin_sword",
    "Paracesis":"paracesis",
    "Plasma Sword":"plasma_sword",
    "Prova":"prova",
    "Prisma Dual Cleavers":"prisma_dual_cleavers",
    "Prisma Obex":"prisma_obex",
    "Prisma Skana":"prisma_skana",
    "Rakta Dark Dagger":"rakta_dark_dagger",
    "Redeemer":"redeemer",
    "Reaper Prime":"reaper_prime",
    "Ripkas":"ripkas",
    "Sarpa":"sarpa",
    "Scindo":"scindo",
    "Serro":"serro",
    "Sheev":"sheev",
    "Silva & Aegis":"silva_aegis",
    "Skana":"skana",
    "Scoliac":"scoliac",
    "Sibear":"sibear",
    "Sigma & Octantis":"sigma_octantis",
    "Silva & Aegis Prime":"silva_aegis_prime",
    "Synoid Heliocor":"synoid_heliocor",
    "Tatsu":"tatsu",
    "Tekko":"tekko",
    "Telos Boltace":"telos_boltace",
    "Tenet Agendus":"tenet_agendus",
    "Tenet Exec":"tenet_exec",
    "Tenet Grigori":"tenet_grigori",
    "Tenet Livia":"tenet_livia",
    "Tipedo":"tipedo",
    "Tonbo":"tonbo",
    "Twin Basolk":"twin_basolk",
    "Twin Krohkur":"twin_krohkur",
    "Venka":"venka",
    "Volnus":"volnus",
    "War":"war",
    "Wolf Sledge":"wolf_sledge",
    "Xoris":"xoris",
    "Zenistar":"zenistar"
}
