riven_attributes = {
  "Positive:": "positive:",
  "Ammo Maximum": "ammo_maximum",
  "Cold": "cold",
  "Critical Chance": "critical_chance",
  "Critical Damage": "critical_damage",
  "Damage": "damage",
  "Damage to Corpus": "damage_to_corpus",
  "Damage to Grineer": "damage_to_grineer",
  "Damage to Infested": "damage_to_infested",
  "Electricity": "electricity",
  "Fire Rate / Attack Speed": "fire_rate_/_attack_speed",
  "Heat": "heat",
  "Impact": "impact",
  "Magazine Capacity": "magazine_capacity",
  "Multishot": "multishot",
  "Projectile speed": "projectile_speed",
  "Punch Through": "punch_through",
  "Puncture": "puncture",
  "Reload Speed": "reload_speed",
  "Slash": "slash",
  "Status Chance": "status_chance",
  "Status Duration": "status_duration",
  "Toxin": "toxin",
  "Weapon Recoil": "weapon_recoil",
  "Zoom": "zoom",
  "Additional Combo Count Chance": "additional_combo_count_chance",
  "Combo Duration": "combo_duration",
  "Critical Chance for Slide Attack": "critical_chance_for_slide_attack",
  "Finisher Damage": "finisher_damage",
  "Heavy Attack Efficiency": "heavy_attack_efficiency",
  "Initial combo": "initial_combo",
  "Range": "range",
  "Negative:": "negative:",
  "Has Negative": "has_negative",
  "No Negative": "no_negative",
}
