name: Run Scraper Every 2 Minutes from 10 AM to 2 AM

on:
  schedule:
    - cron: '*/2 10-23 * * *'
    - cron: '*/2 0-1 * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Check out code
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Step 3: Install dependencies from requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run the scraper script
      - name: Run scraper script
        env:
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
        run: |
          chmod +x riven
          ./riven

