name: Run Scraper Every 2 Minutes for 1 Hour

on:
  schedule:
    # Run the script every 2 minutes for 1 hour (from 9 AM to 10 AM UTC)
    - cron: '*/2 9 * * *' # This cron expression means every 2 minutes from 9 AM to 10 AM UTC

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Check out code
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Step 3: Install dependencies from requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run the scraper script
      - name: Run scraper script
        run: |
          python scraper.py

