name: Run Scraper Every 2 Minutes from 10 AM to 2 AM

on:
  schedule:
    # Run the script every 2 minutes from 10 AM to 2 AM UTC
    - cron: '*/2 10-23 * * *' # 10 AM to 11 PM UTC
    - cron: '*/2 0-1 * * *'   # Midnight to 2 AM UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Check out code
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Step 3: Install dependencies from requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run the scraper script
      - name: Run scraper script
        run: |
          python scraper.py


          name: Run Scraper Every 2 Minutes from 10 AM to 2 AM

